name: Build and Deploy

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test-code:
    name: Build and test application code
    # use system defined below in the tests matrix
    runs-on: ${{ matrix.os }}

    strategy:
      # define the test matrix
      matrix:
        # selected operation systems to run CI
        os: [ubuntu-latest]
        # selected node version to run CI
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          # use the node version defined in matrix above
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn --prefer-offline

      - name: Build
        run: yarn build
        env:
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_PRODUCT_PRICE_ID: ${{ secrets.STRIPE_PRODUCT_PRICE_ID }}
          GATSBY_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          GATSBY_STRIPE_PRODUCT_PRICE_ID: ${{ secrets.STRIPE_PRODUCT_PRICE_ID }}

      - name: Lint
        run: yarn lint

      - name: Build & Deploy docs preview
        run: yarn deploy
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Build & Deploy docs
        run: yarn deploy:prod
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
